import { jsx as _jsx } from "react/jsx-runtime";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import "./index.css";
import App from "./App";
import { Provider } from "react-redux";
import { store } from "./store/store";
createRoot(document.getElementById("root")).render(_jsx(Provider, { store: store, children: _jsx(StrictMode, { children: _jsx(MantineProvider, { children: _jsx(App, {}) }) }) }));
